#15: RIPE Blender API setup and useful methods
ripe-tech/ripe-blender-api-js pull request #1
Opened 2022-04-22 08:22 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-orchestra/issues/15 |
| Dependencies | -- |
| Decisions | - Project setup<br>- Methods to endpoints /load and /render |
| Animated GIF | -- |

2022-04-23 12:04 UTC, joao-conde requested changes
Reviewing, but I will take care of the fixes since @BeeMargarida is on a well-deserved vacation

2022-04-23 12:04 UTC, joao-conde commented on .gitignore
> +package-lock.json
Maybe swap

2022-04-23 12:04 UTC, joao-conde commented on js/load.js
> +            const url = this.invoicingBaseUrl + "load";
this.base_url

2022-04-23 12:04 UTC, joao-conde commented on js/render.js
> +            const url = this.invoicingBaseUrl + "render";
this.base_url

2022-04-23 12:04 UTC, joao-conde commented on package.json
> +    "description": "The RIPE Invoice Express API client",
The RIPE Blender API client

2022-04-23 12:04 UTC, joao-conde commented on rollup.config.js
> +            name: "ripeInvoiceExpress",
ripeBlender

2022-04-26 09:46 UTC, joao-conde approved these changes

2022-04-26 10:00 UTC, 3rdvision approved these changes

2022-04-26 10:12 UTC, joamag approved these changes

2022-04-26 10:12 UTC, merged